### ISSUE TITLE
Not properly sliding

### ISSUE THREAD

**Issue by rupach** [crowdfavorite/wp-drafts-dropdown#2]
Not properly sliding in admin bar in newer wordpress version.

**Comment by rupach** [comment]
I thought its not sliding properly but this is the feature of plugin, when clicked it slide down upto 400px and then dynamically calculate height of the content area and again slide up.

Should I close this issue, please suggest @brichards

**Comment by brichards** [comment]
Yep, sounds like this isn't actually an issue. Closing out!
