### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by rupach** [crowdfavorite/wp-drafts-dropdown#3]
Z-index needs elevated : When using the default theme for WordPress, the Z-index of the text in the drafts list falls behind the logo and behind the title and behind the search box.

https://wordpress.org/support/topic/plugin-drafts-dropdown-z-index-needs-elivated

**Comment by rupach** [comment]
Here is PR https://github.com/crowdfavorite/wp-drafts-dropdown/pull/4
Please review @brichards

**Comment by brichards** [comment]
Fixed via #4
